language: node_js
node_js:
  - "lts/*"
cache: yarn
jobs:
  include:
    - stage: Lint & Unit Tests
      script:
        - yarn run lint
        - yarn test:unit
    - stage: Spec Tests
      script:
        - ./scripts/ci-install-spec-test-dependencies.sh
        - yarn test:spec
