language: node_js
node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules
    - packages/lodestar/node_modules

install:
    - yarn
    - lerna bootstrap

jobs:
  include:
    - stage: Lint and Check types
      name: Check types
      script: lerna run check-types && lerna run lint
      git:
        submodules: false

    - stage: Tests
      name: Unit
      script: lerna run test:unit && lerna run coverage
      git:
        submodules: false
    -
      name: e2e
      script: lerna run test:e2e
      git:
        submodules: false
    -
      name: spec
      script: lerna run test:spec
      git:
        submodules: true

before_deploy: lerna run --scope @chainsafe/lodestar build:docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_PAGES_TOKEN
  keep_history: true
  local_dir: packages/lodestar/docs
  on:
    branch: master
