version: "3.4"
services:
  lodestar:
    build: .
    restart: always
    volumes:
      - lodestar:/root/.local/share/lodestar
    command: beacon --network ${NETWORK:-pyrmont}
  validator:
    build: .
    restart: always
    volumes:
      - lodestar:/root/.local/share/lodestar
    command: validator --network ${NETWORK:-pyrmont} --graffiti "lodestar wuz here"

  prometheus:
    build: docker/prometheus
    restart: always
    volumes:
      - "prometheus:/prometheus"
    depends_on:
      - lodestar

  grafana:
    build: docker/grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "grafana:/var/lib/grafana"
    depends_on:
      - prometheus

volumes:
  lodestar:
  prometheus:
  grafana:
