version: "3.4"
services:
  lodestar:
    build: .
    restart: always
    volumes:
      - lodestar:/usr/app/.${TESTNET:-spadina}
    command: beacon --testnet ${TESTNET:-spadina}

  prometheus:
    build: docker/prometheus
    restart: always
    volumes:
      - "prometheus:/prometheus"
    depends_on:
      - lodestar

  grafana:
    build: docker/grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "grafana:/var/lib/grafana"
    depends_on:
      - prometheus

volumes:
  lodestar:
  prometheus:
  grafana:
