version: "2"
services:
  lodestar:
    build: .
    volumes:
      - lodestar:/usr/app/.spadina
    command: beacon --testnet spadina
    ports:
      - "8008:8008"

  prometheus:
    image: prom/prometheus:latest
    depends_on:
      - lodestar
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  lodestar:
  prometheus:
