name: Mainnet spec tests

on:
  push:
    branches:
      master

jobs:
  specTest:
    runs-on: ubuntu-latest
    steps:
    - run: ./scripts/free-disk-space.sh
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12.14.1'
    - name: Restore dependencies
      uses: actions/cache@master
      id: cache-deps
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Bootstrap
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
    - name: Build
      run: node_modules/.bin/lerna run build
      if: steps.cache-deps.outputs.cache-hit == 'true'
    - name: Mainnet-slow Spec tests
      run: node_modules/.bin/lerna run test:spec-main
    - name: Mainnet-fast tests
      run: node_modules/.bin/lerna run test:spec-fast
