name: CI Tests

on:
  push:
    branches:
      master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Bootstrap
      uses: wemeetagain/actions-lerna@v0.1.0
      with:
        cmd: bootstrap
    - name: Spec tests
      uses: wemeetagain/actions-lerna@v0.1.0
      with:
          cmd: run test:spec-main
