name: CI Tests

on: [pull_request, push]

jobs:
  build:
    name: Quick tests
    runs-on: ubuntu-latest
    steps:
      - run: ./scripts/free-disk-space.sh
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.14.1"
      - name: Restore dependencies
        uses: actions/cache@master
        id: cache-deps
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Bootstrap
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - uses: actions/upload-artifact@master
        with:
          name: built-src
          path: .

  unitTest:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      GOERLI_RPC_URL: ${{ secrets.GOERLI_RPC_URL }}
    steps:
      - uses: actions/download-artifact@master
        with:
          name: built-src
          path: .
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test:unit
      - name: Coverage
        run: node_modules/.bin/lerna run coverage
      - name: E2e tests
        run: yarn test:e2e
      - name: E2e simulation tests
        run: yarn test:e2e:sim
      - name: Spec tests
        run: node_modules/.bin/lerna run test:spec-min

  specTests:
    name: Spec tests
    runs-on: ubuntu-latest
    steps:
      - run: ./scripts/free-disk-space.sh
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.14.1"
      - name: Restore dependencies
        uses: actions/cache@master
        id: cache-deps
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Bootstrap
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Build
        run: node_modules/.bin/lerna run build
        if: steps.cache-deps.outputs.cache-hit == 'true'
      - name: Spec tests mainnet fast
        run: node_modules/.bin/lerna run test:spec-fast
