name: Tests

on: [pull_request, push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      # <common-build> - Uses YAML anchors in the future
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.14.1"
      - name: Restore dependencies
        uses: actions/cache@master
        id: cache-deps
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-ignore-optional
      - name: Install & build
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --ignore-optional
      - name: Build
        run: node_modules/.bin/lerna run build
        if: steps.cache-deps.outputs.cache-hit == 'true'
      # </common-build>
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test:unit
      - name: Upload coverage data
        run: yarn coverage
      - name: E2e tests
        run: yarn test:e2e
      - name: E2e simulation tests
        run: yarn test:e2e:sim

  spec-min:
    name: Spec min
    runs-on: ubuntu-latest
    steps:
      # <common-build> - Uses YAML anchors in the future
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.14.1"
      - run: ./scripts/free-disk-space.sh
      - name: Restore dependencies
        uses: actions/cache@master
        id: cache-deps
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install & build
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Build
        run: node_modules/.bin/lerna run build
        if: steps.cache-deps.outputs.cache-hit == 'true'
      # </common-build>
      - run: yarn test:spec-min

  spec-fast:
    name: Spec fast
    runs-on: ubuntu-latest
    steps:
      # <common-build> - Uses YAML anchors in the future
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.14.1"
      - run: ./scripts/free-disk-space.sh
      - name: Restore dependencies
        uses: actions/cache@master
        id: cache-deps
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install & build
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Build
        run: node_modules/.bin/lerna run build
        if: steps.cache-deps.outputs.cache-hit == 'true'
      # </common-build>
      - run: yarn test:spec-fast

  spec-main:
    name: Spec main
    runs-on: ubuntu-latest
    if: github.ref == 'ref/head/master' && github.event_name == 'push'
    steps:
      # <common-build> - Uses YAML anchors in the future
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.14.1"
      - run: ./scripts/free-disk-space.sh
      - name: Restore dependencies
        uses: actions/cache@master
        id: cache-deps
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install & build
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Build
        run: node_modules/.bin/lerna run build
        if: steps.cache-deps.outputs.cache-hit == 'true'
      # </common-build>
      - run: yarn test:spec-main
