name: CI Tests

on: [pull_request, push]

jobs:
  # First previous test that ensures src builds, lint ok, unit test ok
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      # <common-build> - Uses YAML anchors in the future
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.14.1"
      - name: Restore dependencies
        uses: actions/cache@master
        id: cache-deps
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install & build
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --ignore-optional
      - name: Build
        run: node_modules/.bin/lerna run build
        if: steps.cache-deps.outputs.cache-hit == 'true'
      # </common-build>
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn test:unit
      - name: Upload coverage data
        run: yarn coverage

  # Run expensive e2e and spec in paralel after unit tests are ok
  tests:
    name: Test
    runs-on: ubuntu-latest
    needs: [unit-test]
    strategy:
      fail-fast: false
      matrix:
        cmd: [
          'test:e2e',
          'test:e2e:sim',
          'test:spec-min',
          'test:spec-fast',
          'test:spec-main'
        ]
    steps:
      # <common-build> - Uses YAML anchors in the future
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.14.1"
      - name: Restore dependencies
        uses: actions/cache@master
        id: cache-deps
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install & build
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Build
        run: node_modules/.bin/lerna run build
        if: steps.cache-deps.outputs.cache-hit == 'true'
      # </common-build>
      - run: ./scripts/free-disk-space.sh
        if: contains(matrix.cmd, 'test:spec')
      - run: yarn ${{ matrix.cmd }}
