name: CI Tests

on: [pull_request, pull]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Bootstrap
      uses: wemeetagain/actions-lerna@v0.1.0
      with:
        cmd: bootstrap
    - name: Check types
      uses: wemeetagain/actions-lerna@v0.1.0
      with:
        cmd: run check-types
    - name: Lint
      uses: wemeetagain/actions-lerna@v0.1.0
      with:
        cmd: run lint

  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Bootstrap
      uses: wemeetagain/actions-lerna@v0.1.0
      with:
        cmd: bootstrap
    - name: Unit tests
      uses: wemeetagain/actions-lerna@v0.1.0
      with:
          cmd: run test:unit
    - name: Coverage
      uses: wemeetagain/actions-lerna@v0.1.0
      with:
          cmd: run coverage
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Bootstrap
      uses: wemeetagain/actions-lerna@v0.1.0
      with:
        cmd: bootstrap
    - name: E2e tests
      uses: wemeetagain/actions-lerna@v0.1.0
      with:
          cmd: run test:e2e

  specMin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Bootstrap
      uses: wemeetagain/actions-lerna@v0.1.0
      with:
        cmd: bootstrap
    - name: Spec tests
      uses: wemeetagain/actions-lerna@v0.1.0
      with:
          cmd: run test:spec-min
