name: CI Tests

on: [pull_request, push]

jobs:
  lint:
    name: Quick tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install lerna
      run: yarn global add lerna
    - name: Bootstrap
      run: lerna bootstrap
    - name: Check types
      run: lerna run check-types
    - name: Lint
      run: lerna run lint
    - name: Unit tests
      run: lerna run test:unit
    - name: Coverage
      run: lerna run coverage
    - name: E2e tests
      run: lerna run test:e2e

  specMin:
    name: Minimal spec tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install lerna
      run: yarn global add lerna
    - name: Bootstrap
      run: lerna bootstrap
    - name: Spec tests
      run: lerna run test:spec-min
