name: CI Tests

on: [pull_request, push]

jobs:
  lint:
    name: Quick tests
    runs-on: ubuntu-latest
    steps:
    - name: Free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
    - uses: actions/checkout@v1
    - name: Install lerna
      run: yarn global add lerna
    - name: Restore dependencies
      uses: actions/cache@master
      id: cache-deps
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Bootstrap
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: $(yarn global bin)/lerna bootstrap
    - name: Build
      run: $(yarn global bin)/lerna run build
      if: steps.cache-deps.outputs.cache-hit == 'true'
    - name: Lint
      run: $(yarn global bin)/lerna run lint
    - name: Unit tests
      run: $(yarn global bin)/lerna run test:unit
    - name: Coverage
      run: $(yarn global bin)/lerna run coverage
    - name: E2e tests
      run: $(yarn global bin)/lerna run test:e2e
    - name: Spec tests
      run: $(yarn global bin)/lerna run test:spec-min
